# Generated by Django 5.1.6 on 2025-04-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='serviceprovider_photos/'),
        ),
    ]
