# Generated by Django 5.1.6 on 2025-07-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('serviceprovider', '0002_serviceprovider_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='serviceprovider_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='serviceprovider_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
