# Generated by Django 5.1.6 on 2025-07-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('serviceprovider', '0003_serviceprovider_groups_serviceprovider_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='serviceprovider_users', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='serviceprovider_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
