# Generated by Django 5.1.6 on 2025-07-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider', '0004_alter_serviceprovider_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
